### ISSUE TITLE
version heading should use h2 level

### ISSUE THREAD

**Issue by NateScarlet** [conventional-changelog/standard-version#317]
![image](https://user-images.githubusercontent.com/21083014/55128636-32ea6880-514f-11e9-890d-bd8eccc79e93.png)

![image](https://user-images.githubusercontent.com/21083014/55128593-13534000-514f-11e9-9bf0-6a93da49c1d3.png)

**Comment by stevemao** [comment]
I believe it was fixed by https://github.com/conventional-changelog/conventional-changelog/pull/237. Are you on the latest version?

**Comment by NateScarlet** [comment]
```
+-- standard-version@5.0.2
| +-- chalk@2.4.2
| | +-- ansi-styles@3.2.1 deduped
| | +-- escape-string-regexp@1.0.5 deduped
| | `-- supports-color@5.5.0
| |   `-- has-flag@3.0.0 deduped
| +-- conventional-changelog@3.0.6
```

**Comment by NateScarlet** [comment]
Found duplicate with #208

**Comment by jcornaz** [comment]
It is obviouls not solved. 

Look at verion `8.0.2` in standard-version's changelog: https://raw.githubusercontent.com/conventional-changelog/standard-version/91cd83c35145b733cd2407f106ebe43b5ce3edc5/CHANGELOG.md

@stevemao Can you reopen the issue?

**Comment by tonai** [comment]
I just test this package I found really great, but I think the header problem is still present.
See https://github.com/tonai/react-deploy/commit/9057ee81875c4972d26da658c75c3828156ab99e
I have `### 0.1.1 (2020-10-13)` but it should be `## 0.1.1 (2020-10-13)`

**Comment by tonai** [comment]
Ok I miss the fact that for the first release you shouls run `npm run release -- --first-release`.
It looks better: https://github.com/tonai/react-deploy/commit/797d7240ec3c5df3b6897fa7f0e9c7a0b7513748

**Comment by tonai** [comment]
It still looks a little odd for patch releases: https://github.com/tonai/react-deploy/commit/b44911e45ca9861df4cc191aa116e5381e8c8de0

It is ok for minor release: https://github.com/tonai/react-deploy/commit/2cdadf4acff8940bc648e6570fe8be32fdbafa79

Is it something that is wanted ?

**Comment by weareoutman** [comment]
The `Bug Fixes` heading should be a subheading of the release `0.1.2`, but now they are at the same level. This also caused bots like renovatebot [failed to parse the changelog](https://github.com/renovatebot/renovate/issues/5181).

```markdown
### 0.1.2

### Bug Fixes

* some fixes.
```

**Comment by rwanito** [comment]
Hi ! 
I have the same problem !

Is it fixed ?
Thanks !

**Comment by NateScarlet** [comment]
[changes that fix this problem](https://github.com/conventional-changelog/conventional-changelog/commit/b5951fb5c58ada8d480d17213703d717acb1cd42#diff-1a025fc5a97f17b31249584fa2b6c6dd25361189201fff4d87c723bb368b5deb) is not included in `conventional-changelog-core@4.2.2`

for now, i use a postchangelog script:

```
sed -r -e 's/^#{1,3} \[/## [/' -i CHANGELOG.md
```

**Comment by rwanito** [comment]
Any updates about that ?
thanks !

**Comment by amokmen** [comment]
> ```
> sed -r -e 's/^#{1,3} \[/## [/' -i CHANGELOG.md
> ```

Spent 2 hours fighting backslash "\" problem!

It's not working if directly included in `.versionrc.js` as
```js
module.exports = {
  scripts: {
    postchangelog: "sed -r -e 's/^#{1,3} \[/## [/' -i CHANGELOG.md",
  },
};
```
Because there are 2 problems arise:
1) _Prettier_ automatically SILENTLY REMOVES **backslash** symbol from string!
2) _NodeJS 14.16.0 REPL_ and _standard-version_ incorrectly works with backslash in string too (removing it).

I put this shell-command line into **external file** - this removed both problems.

So, now it looks like:
```js
module.exports = {
  scripts: {
    postchangelog: "./tools/for_standard-version.sh",
  },
};
```

**Comment by NateScarlet** [comment]
@amokmen

use `bash ./tools/for_standard-version.sh` if you want be windows compatible (git-bash almost always installed, otherwise it may not run due to some encoding issue).

![image](https://user-images.githubusercontent.com/21083014/115537552-80edde00-a2cd-11eb-971c-7ecf3eb18836.png)

**Comment by amokmen** [comment]
@NateScarlet 
I am personally using WSL (Ubuntu) at Windows desktop, so for me all working without adding prefix "bash ".

P. S. As for me - trying "native" Windows-based development is a bad idea in general. There are a lot of problems in Linux-based development, so multiplying problems with Windows is not helping at all :)

**Comment by josteph** [comment]
I'm not sure why does conventional changelog template need `isPatch` treatment here. If somebody could explain the reasoning behind this, then this answers other issues regarding heading level as well.

https://github.com/conventional-changelog/conventional-changelog/blob/master/packages/conventional-changelog-conventionalcommits/templates/header.hbs#L1

**Comment by zavoloklom** [comment]
Small addition to @amokmen advise.

There is a problem with that script and MacOS `sed: -i may not be used with stdin`. So if you want to use script both in Linux and Mac you should do:

```
"scripts": {
    "postchangelog": "if [[ \"$OSTYPE\" == \"darwin\"* ]]; then SEDOPTION=\"''\"; fi && sed -i $SEDOPTION -re 's/^#{1,3} \\[/## [/' ./CHANGELOG.md"
  }
```

**Comment by ciltocruz** [comment]
What about this?
