### ISSUE TITLE
npx standard-version - compareUrlFormat and type etc .. ignored

### ISSUE THREAD

**Issue by dlarr** [conventional-changelog/standard-version#635]
Hello, I am try to generated a changelog with this signle command line, for the sake of readness i've put new line before eache parameter.

```
npx standard-version 
   --skip.commit=true
   --skip.tag=true 
   --preset angular 
   --compareUrlFormat="https://BITBUCKET_URL/projects/{{owner}}/repos/{{repository}}//compare/diff?targetBranch=refs%2Ftags%2F{{previousTag}}&sourceBranch=refs%2Ftags%2F{{currentTag}}" 
   --types=[{"type":"chore","section":"Buildprocesschanges","hidden":false},{"type":"revert","section":"Reverts","hidden":false}]
```

The changelog is generated but the parameters seems to not be used (a part from skip and preset which work)
Generation still provided with the wrong URL format, and the type are not taken into account.

Also I've try to put this in a .versionrc.json which is still ignored

Am I doing something wrong ? 

```
// .versionrc.json
{
  "types": [
    {"type": "chore", "section":"Build process changes", "hidden": false},
    {"type": "revert", "section":"Reverts", "hidden": false},
    {"type": "feat", "section": "Features", "hidden": false},
    {"type": "fix", "section": "Bug Fixes", "hidden": false},
    {"type": "improvement", "section": "Feature Improvements", "hidden": false},
    {"type": "docs", "section":"Docs", "hidden": false},
    {"type": "style", "section":"Styling", "hidden": false},
    {"type": "refactor", "section":"Code Refactoring", "hidden": false},
    {"type": "perf", "section":"Performance Improvements", "hidden": false},
    {"type": "test", "section":"Tests", "hidden": false},
    {"type": "build", "section":"Build System", "hidden": false},
    {"type": "ci", "section":"CI", "hidden":false},
    {"type": "quality", "section":"Quality fixes", "hidden":false}
  ],
  "compareUrlFormat":  "https://BITBUCKET_URL/projects/{{owner}}/repos/{{repository}}//compare/diff?targetBranch=refs%2Ftags%2F{{previousTag}}&sourceBranch=refs%2Ftags%2F{{currentTag}}",
  "issueUrlFormat": "{{id}}"
}

```

**Comment by stroym** [comment]
@dlarr In my experience .versionrc.json doesn't work (maybe if you include it in bumpfiles in manifest.json/package.json), try using just .versionrc. The JSON you've got there looks fine to me otherwise. I've only ever needed to customize types, so those at the very least should be working fine - though there's no reason for the custom urls to not work.
As for using the --types argument, I can't get it to work no matter what either and it's quite frustrating.

**Comment by dlarr** [comment]
Hello and thanks for answer. But i've tried also without the .json and it's the same.

Also i use this lib for a java app, so i don't have a package.json, which of course i would like to keep that way.

To date I still can't figure it out.

**Comment by dlarr** [comment]
Ok for the types, it doesn't override the preset part :/

I chose an angular preset, which means you just get the features, the bugfixes  and the reverts commits.

Removing the preset make the commits appears properly

**Comment by dlarr** [comment]
It's allright I got it all to work as Intended

```
// .versionrc
{
  "header": "What ever you want at the top of your changelog",
  "types": [
      {"type": "chore", "section":"Build process changes", "hidden":false},
      {"type": "revert", "section":"Reverts", "hidden":false},
      {"type": "feat", "section":"Features", "hidden":false},
      {"type": "fix", "section":"BugFixes", "hidden":false},
      {"type": "improvement", "section":"FeatureImprovements", "hidden":false},
      {"type": "docs", "section":"Docs", "hidden":false},
      {"type": "style", "section":"Styling", "hidden":false},
      {"type": "refactor", "section":"CodeRefactoring", "hidden":false},
      {"type": "perf", "section":"PerformanceImprovements", "hidden":false},
      {"type": "test", "section":"Tests", "hidden":false},
      {"type": "build", "section":"BuildSystem", "hidden":false},
      {"type": "ci", "section": "CI", "hidden":false},
      {"type": "quality", "section": "Qualityfixes", "hidden":false}
  ],
  "compareUrlFormat":  "https://BITBUCKET_URL/projects/{{owner}}/repos/{{repository}}/compare/diff?targetBranch=refs%2Ftags%2F{{previousTag}}&sourceBranch=refs%2Ftags%2F{{currentTag}}",
  "issueUrlFormat": "https://JIRA_URL/browse/{{id}}",
  "commitUrlFormat": "https://BITBUCKET_URL/projects/{{owner}}/repos/{{repository}}/commits/{{hash}}",
  "skip": {
    "commit": true,
    "tag": true
  }
}

```

And then you just run : npx standard-version.

Works pretty well :)

Thanks, I am closing the issue
